[package]
name = "treehouse-observer"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
treehouse-application-model = { path = "../treehouse-application-model" }
treehouse-drift = { path = "../treehouse-drift" }
treehouse-graph = { path = "../treehouse-graph" }
treehouse-model-inference = { path = "../treehouse-model-inference" }
treehouse-parser = { path = "../treehouse-parser" }
treehouse-subsystem-engine = { path = "../treehouse-subsystem-engine" }
treehouse-system-graph = { path = "../treehouse-system-graph" }
